/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ErrorResponse */
        ErrorResponse: {
            /** Error */
            error: string;
        };
        /** Game */
        Game: {
            black: components["schemas"]["GamePlayer"];
            /**
             * Eco
             * @default null
             */
            eco: string | null;
            /**
             * End Time
             * @default null
             */
            end_time: number | null;
            /**
             * Fen
             * @default null
             */
            fen: string | null;
            /**
             * Initial Setup
             * @default null
             */
            initial_setup: string | null;
            /** Pgn */
            pgn: string;
            /**
             * Rated
             * @default null
             */
            rated: boolean | null;
            /**
             * Rules
             * @default null
             */
            rules: string | null;
            /**
             * Tcn
             * @default null
             */
            tcn: string | null;
            /**
             * Time Class
             * @default null
             */
            time_class: string | null;
            /**
             * Time Control
             * @default null
             */
            time_control: string | null;
            /** Url */
            url: string;
            /**
             * Uuid
             * @default null
             */
            uuid: string | null;
            white: components["schemas"]["GamePlayer"];
        } & {
            [key: string]: unknown;
        };
        /** GamePlayer */
        GamePlayer: {
            /**
             * @Id
             * @default null
             */
            "@id": string | null;
            /**
             * Rating
             * @default null
             */
            rating: number | null;
            /**
             * Result
             * @default null
             */
            result: string | null;
            /** Username */
            username: string;
            /**
             * Uuid
             * @default null
             */
            uuid: string | null;
        } & {
            [key: string]: unknown;
        };
        /** GamesResponse */
        GamesResponse: {
            /**
             * Archive
             * @default null
             */
            archive: string | null;
            /** Games */
            games: components["schemas"]["Game"][];
            pagination: components["schemas"]["Pagination"];
            /** Username */
            username: string;
        } & {
            [key: string]: unknown;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** Pagination */
        Pagination: {
            /** Has Next */
            has_next: boolean;
            /** Has Previous */
            has_previous: boolean;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Games */
            total_games: number;
            /** Total Pages */
            total_pages: number;
        } & {
            [key: string]: unknown;
        };
        /** UserProfile */
        UserProfile: {
            /** @Id */
            "@id": string;
            /**
             * Avatar
             * @default null
             */
            avatar: string | null;
            /**
             * Country
             * @default null
             */
            country: string | null;
            /**
             * Fide
             * @default null
             */
            fide: number | null;
            /** Followers */
            followers: number;
            /**
             * Is Streamer
             * @default false
             */
            is_streamer: boolean;
            /** Joined */
            joined: number;
            /** Last Online */
            last_online: number;
            /**
             * League
             * @default null
             */
            league: string | null;
            /**
             * Location
             * @default null
             */
            location: string | null;
            /**
             * Name
             * @default null
             */
            name: string | null;
            /** Player Id */
            player_id: number;
            /** Status */
            status: string;
            /** Streaming Platforms */
            streaming_platforms?: unknown[];
            /**
             * Title
             * @default null
             */
            title: string | null;
            /**
             * Twitch Url
             * @default null
             */
            twitch_url: string | null;
            /** Url */
            url: string;
            /** Username */
            username: string;
            /**
             * Verified
             * @default null
             */
            verified: boolean | null;
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description Chess.com could not be reached or returned invalid data. */
        ExternalAPIError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The page or page_size query parameter is invalid. */
        InvalidPagination: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description One-based page number. */
        Page: number;
        /** @description Number of games per page. Maximum 100. */
        PageSize: number;
        /** @description Chess.com username. */
        Username: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chess.com username. */
                username: components["parameters"]["Username"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chess.com player profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            502: components["responses"]["ExternalAPIError"];
        };
    };
    getGames: {
        parameters: {
            query?: {
                /** @description One-based page number. */
                page?: components["parameters"]["Page"];
                /** @description Number of games per page. Maximum 100. */
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                /** @description Chess.com username. */
                username: components["parameters"]["Username"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest monthly games, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GamesResponse"];
                };
            };
            400: components["responses"]["InvalidPagination"];
            502: components["responses"]["ExternalAPIError"];
        };
    };
}
